name: Thesis
channels:
  - defaults
  - ambermd
dependencies:
  - python=3.7
  - biopython
  - matplotlib
  - pytraj
  - pip
  - certifi
  - numpy
  - scipy
  - seaborn
  - pip:
    - -r file:requirements.txt
    
